### ISSUE TITLE
can't start this container

### ISSUE THREAD

**Issue by TerrificMao** [alanwds/aws-cost-exporter#1]
Traceback (most recent call last): File "./aws-cost-exporter.py", line 96, in <module> start_http_server(port) File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 193, in start_http_server httpd = _ThreadingSimpleServer((addr, port), CustomMetricsHandler) File "/usr/local/lib/python3.8/socketserver.py", line 452, in __init__ self.server_bind() File "/usr/local/lib/python3.8/http/server.py", line 138, in server_bind socketserver.TCPServer.server_bind(self) File "/usr/local/lib/python3.8/socketserver.py", line 466, in server_bind self.socket.bind(self.server_address) TypeError: an integer is required (got type str)

**Comment by alanwds** [comment]
@TerrificMao Looks like you set the PORT env var as empty. Something like `-e PORT=""`. So, the socket server as reciving an empty string insted of an integer (a port numer e.g. 8080).

You should use without this env var (so, it will use the default port: 9150). If you want customize that (e.g. 8080), you should use `-e PORT="8080"`

Regards
